pull_request_rules:
  - name: automatic merge for master when reviewed and CI passes and has label
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - "#approved-reviews-by>=1"
      - base=master
      - label=ready-to-merge
    actions:
      merge:
        method: rebase
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request is now in conflicts. Could you fix it? 🙏
  - name: automatic merge for Dependabot pull requests with label
    conditions:
      - label=ready-to-merge
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=continuous-integration/travis-ci/pr
    actions:
      merge:
        method: rebase
